extends Node

class_name Canciones

var canciones: Array[Dictionary] = [
	# Please Please Me (1963)
	{ "titulo": "I Saw Her Standing There", "album": "Please Please Me" },
	{ "titulo": "Misery", "album": "Please Please Me" },
	{ "titulo": "Anna (Go to Him)", "album": "Please Please Me" },
	{ "titulo": "Chains", "album": "Please Please Me" },
	{ "titulo": "Boys", "album": "Please Please Me" },
	{ "titulo": "Ask Me Why", "album": "Please Please Me" },
	{ "titulo": "Please Please Me", "album": "Please Please Me" },
	{ "titulo": "Love Me Do", "album": "Please Please Me" },
	{ "titulo": "P.S. I Love You", "album": "Please Please Me" },
	{ "titulo": "Baby It's You", "album": "Please Please Me" },
	{ "titulo": "Do You Want to Know a Secret", "album": "Please Please Me" },
	{ "titulo": "A Taste of Honey", "album": "Please Please Me" },
	{ "titulo": "There's a Place", "album": "Please Please Me" },
	{ "titulo": "Twist and Shout", "album": "Please Please Me" },

	# With The Beatles (1963)
	{ "titulo": "It Won't Be Long", "album": "With The Beatles" },
	{ "titulo": "All I've Got to Do", "album": "With The Beatles" },
	{ "titulo": "All My Loving", "album": "With The Beatles" },
	{ "titulo": "Don't Bother Me", "album": "With The Beatles" },
	{ "titulo": "Little Child", "album": "With The Beatles" },
	{ "titulo": "Till There Was You", "album": "With The Beatles" },
	{ "titulo": "Please Mister Postman", "album": "With The Beatles" },
	{ "titulo": "Roll Over Beethoven", "album": "With The Beatles" },
	{ "titulo": "Hold Me Tight", "album": "With The Beatles" },
	{ "titulo": "You Really Got a Hold on Me", "album": "With The Beatles" },
	{ "titulo": "I Wanna Be Your Man", "album": "With The Beatles" },
	{ "titulo": "Devil in Her Heart", "album": "With The Beatles" },
	{ "titulo": "Not a Second Time", "album": "With The Beatles" },
	{ "titulo": "Money (That's What I Want)", "album": "With The Beatles" },

	# A Hard Day's Night (1964)
	{ "titulo": "A Hard Day's Night", "album": "A Hard Day's Night" },
	{ "titulo": "I Should Have Known Better", "album": "A Hard Day's Night" },
	{ "titulo": "If I Fell", "album": "A Hard Day's Night" },
	{ "titulo": "I'm Happy Just to Dance with You", "album": "A Hard Day's Night" },
	{ "titulo": "And I Love Her", "album": "A Hard Day's Night" },
	{ "titulo": "Tell Me Why", "album": "A Hard Day's Night" },
	{ "titulo": "Can't Buy Me Love", "album": "A Hard Day's Night" },
	{ "titulo": "Any Time at All", "album": "A Hard Day's Night" },
	{ "titulo": "I'll Cry Instead", "album": "A Hard Day's Night" },
	{ "titulo": "Things We Said Today", "album": "A Hard Day's Night" },
	{ "titulo": "When I Get Home", "album": "A Hard Day's Night" },
	{ "titulo": "You Can't Do That", "album": "A Hard Day's Night" },
	{ "titulo": "I'll Be Back", "album": "A Hard Day's Night" },

	# Beatles for Sale (1964)
	{ "titulo": "No Reply", "album": "Beatles for Sale" },
	{ "titulo": "I'm a Loser", "album": "Beatles for Sale" },
	{ "titulo": "Baby's in Black", "album": "Beatles for Sale" },
	{ "titulo": "Rock and Roll Music", "album": "Beatles for Sale" },
	{ "titulo": "I'll Follow the Sun", "album": "Beatles for Sale" },
	{ "titulo": "Mr. Moonlight", "album": "Beatles for Sale" },
	{ "titulo": "Kansas City/Hey-Hey-Hey-Hey!", "album": "Beatles for Sale" },
	{ "titulo": "Eight Days a Week", "album": "Beatles for Sale" },
	{ "titulo": "Words of Love", "album": "Beatles for Sale" },
	{ "titulo": "Honey Don't", "album": "Beatles for Sale" },
	{ "titulo": "Every Little Thing", "album": "Beatles for Sale" },
	{ "titulo": "I Don't Want to Spoil the Party", "album": "Beatles for Sale" },
	{ "titulo": "What You're Doing", "album": "Beatles for Sale" },
	{ "titulo": "Everybody's Trying to Be My Baby", "album": "Beatles for Sale" },

	# Help! (1965)
	{ "titulo": "Help!", "album": "Help!" },
	{ "titulo": "The Night Before", "album": "Help!" },
	{ "titulo": "You've Got to Hide Your Love Away", "album": "Help!" },
	{ "titulo": "I Need You", "album": "Help!" },
	{ "titulo": "Another Girl", "album": "Help!" },
	{ "titulo": "You're Going to Lose That Girl", "album": "Help!" },
	{ "titulo": "Ticket to Ride", "album": "Help!" },
	{ "titulo": "Act Naturally", "album": "Help!" },
	{ "titulo": "It's Only Love", "album": "Help!" },
	{ "titulo": "You Like Me Too Much", "album": "Help!" },
	{ "titulo": "Tell Me What You See", "album": "Help!" },
	{ "titulo": "I've Just Seen a Face", "album": "Help!" },
	{ "titulo": "Yesterday", "album": "Help!" },
	{ "titulo": "Dizzy Miss Lizzy", "album": "Help!" },

	# Rubber Soul (1965)
	{ "titulo": "Drive My Car", "album": "Rubber Soul" },
	{ "titulo": "Norwegian Wood (This Bird Has Flown)", "album": "Rubber Soul" },
	{ "titulo": "You Won't See Me", "album": "Rubber Soul" },
	{ "titulo": "Nowhere Man", "album": "Rubber Soul" },
	{ "titulo": "Think for Yourself", "album": "Rubber Soul" },
	{ "titulo": "The Word", "album": "Rubber Soul" },
	{ "titulo": "Michelle", "album": "Rubber Soul" },
	{ "titulo": "What Goes On", "album": "Rubber Soul" },
	{ "titulo": "Girl", "album": "Rubber Soul" },
	{ "titulo": "I'm Looking Through You", "album": "Rubber Soul" },
	{ "titulo": "In My Life", "album": "Rubber Soul" },
	{ "titulo": "Wait", "album": "Rubber Soul" },
	{ "titulo": "If I Needed Someone", "album": "Rubber Soul" },
	{ "titulo": "Run for Your Life", "album": "Rubber Soul" },

	# Revolver (1966)
	{ "titulo": "Taxman", "album": "Revolver" },
	{ "titulo": "Eleanor Rigby", "album": "Revolver" },
	{ "titulo": "I'm Only Sleeping", "album": "Revolver" },
	{ "titulo": "Love You To", "album": "Revolver" },
	{ "titulo": "Here, There and Everywhere", "album": "Revolver" },
	{ "titulo": "Yellow Submarine", "album": "Revolver" },
	{ "titulo": "She Said She Said", "album": "Revolver" },
	{ "titulo": "Good Day Sunshine", "album": "Revolver" },
	{ "titulo": "And Your Bird Can Sing", "album": "Revolver" },
	{ "titulo": "For No One", "album": "Revolver" },
	{ "titulo": "Doctor Robert", "album": "Revolver" },
	{ "titulo": "I Want to Tell You", "album": "Revolver" },
	{ "titulo": "Got to Get You into My Life", "album": "Revolver" },
	{ "titulo": "Tomorrow Never Knows", "album": "Revolver" },

	# Sgt. Pepper's Lonely Hearts Club Band (1967)
	{ "titulo": "Sgt. Pepper's Lonely Hearts Club Band", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "With a Little Help from My Friends", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "Lucy in the Sky with Diamonds", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "Getting Better", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "Fixing a Hole", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "She's Leaving Home", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "Being for the Benefit of Mr. Kite!", "album": "Sgt. Pepper's Lonely Hearts Club Band" },
	{ "titulo": "Within You Without You", "album": "Sgt. Pepper's Lonely Hearts Club Band" }]
